#output_path: ./text_outputs/turtle_textfusion_learn_bg_100g_25batch_highreg
output_path: ./text_outputs/btsv_sds_pic
continue_learn: false
seed: 99
# CLIP-related
#text_prompt: a turtle with uniformly green colored background
text_prompt: The face of an Asian guy in his 20s
base_text_prompt: The face of Max Planck
clip_model: ViT-B/32
gpu: 0
#model to use for image embedding space (clip-vit, dino-vit)
consistency_clip_model: ViT-B/32
consistency_vit_stride: 8
consistency_vit_layer: 11
image: ./imgs/bts.png
src_image: ./imgs/spot.png
learn_bg: false
background: [1.,1.,1.]
#['dino', 'clip']
image_encode: clip
#['hidden', 'key', 'query', 'value']
facet: hidden
# Mesh
mesh: ./meshes/max_planck.obj
mesh_local: null
#mesh_local: ./meshes/spot_col.ply
retriangulate: 0
# Render settings
bsdf: diffuse
# Hyper-parameters
#[SDS, DDS]
score: SDS
dds_burnin: 450
negative_prompt: true
lr: 0.0025
epochs: 2500
guidance_scale: 100
clip_weight: .0
image_weight: 100.0
delta_clip_weight: 0
delta_image_weight: 1.0
delta_layers: [5,6,22]
regularize_jacobians_weight: 0.5
consistency_loss_weight: 0
consistency_elev_filter: 30
consistency_azim_filter: 20
batch_size: 15
train_res: 512
resize_method: cubic
# Camera parameters
fov_min: 30.0
fov_max: 90.0
dist_min: 2.5
dist_max: 3.0
light_power: 5.0
elev_alpha: 1.0
elev_beta: 5.0 
elev_max: 60.0
azim_min: 0.0
azim_max: 360.0
aug_loc: 1
aug_light: 1
aug_bkg: 1
adapt_dist: 1

log_interval: 5
log_interval_im: 150
log_elev: 30.0
log_fov: 60.0
log_dist: 3.0
log_res: 512
log_light_power: 3.0